version: "3"

services:     
  server:
    container_name: microfreshener-server
    build: server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    environment:
      - DJANGO_SETTINGS=prod
    ports: 
      - "8000:8000"
    labels:
      - "traefik.frontend.rule=Host:api.microfreshener.localhost"
    networks: 
      - web
  

  client:
    container_name: microfreshener-client
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        configuration: production
    ports:
      - "80:80"
    labels:
      - "traefik.frontend.rule=Host:microfreshener.localhost"
    networks: 
      - web

networks:
  web:
    external: true
  internal:
    external: false
